# Generated by Django 6.0 on 2026-04-01 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Helpers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('skills', models.CharField(max_length=200)),
                ('experience', models.IntegerField()),
                ('price_per_day', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('rating', models.FloatField(default=0)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='helpers/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
